### ISSUE TITLE
publishing different bundleIds to Google Play Console

### ISSUE THREAD

**Issue by JacobDel** [jar0s/reactNative-babel-wla#1]
When you compile your release bundle, does your bundleId actually change?
The package id in AndroidManifest.xml doesn't change, so why would the bundleId change?
Either way, for me google play console doesn't accept any builds because the bundleId isn't changing

**Comment by JacobDel** [comment]
The problem was System.getenv in gradle not working properly, my apologies!

**Comment by jar0s** [comment]
Hi @JacobDel ,
I'm glad you were able to find the root cause of the problem.
I'm curious what you mean by " System.getenv in gradle not working properly", though, and whether it is something that needs to be updated/fixed in the code or was is related to your local environment setup?

**Comment by JacobDel** [comment]
Thanks for your comment.
It is related to my local environment setup.

The bundleId and displayName from line 131 in https://github.com/jar0s/reactNative-babel-wla/blob/master/android_template/app/build.gradle#L131 could not be read properly.
The issue was that I was running the command `sh scripts/load_env.sh && cd android && ./gradlew bundleRelease`.
This basically loaded .env in a subshell, out of reach for the gradle file.
The solution was `. scripts/load_env.sh && cd android && ./gradlew bundleRelease`

**Comment by JacobDel** [comment]
Thanks for your comment.

The environmental variable for bundleId and displayName from line 131 (https://github.com/jar0s/reactNative-babel-wla/blob/master/android_template/app/build.gradle#L131) could not be read properly.
Hardcoding the bundleId and displayName does however solve the issue.

It's strange because the terminal is able to echo the environmental variables but gradlew isn't.
The command I execute is 'echo $BUNDLE_ID cd android && ./gradlew bundleRelease'
Maybe gradlew builds the app in a subshell and therefore the sourced variables aren't accessible?

(operating system: macOS)

**Comment by jar0s** [comment]
That's interesting. If you have the environmental variable set in your terminal then it should be visible by gradle.
I wonder if it comes down to the settings of your shell.

Let me double check locally with a release bundle and I'll get back to you. I must admit I'm mostly building this project in the debug version.

**Comment by jar0s** [comment]
I just tried the following:
1. In the package.json added `"build:android": ". scripts/load_env.sh && cd android && ./gradlew bundleRelease",` in the "scripts" section.
2. Run `yarn configure-brand:android`
3. Run `yarn build:android`
4. Run `java -jar ~/Downloads/bundletool-all-1.14.1.jar dump manifest --bundle ./android/app/build/outputs/bundle/release/app-release.aab > AndroidManifest.xml` (after downloading the bundletool from [here](https://github.com/google/bundletool/releases) )
5. Inspected the manifest file extracted from the bundle and observed it had the `package` and `andoid:label` attributes correctly substituted with values from the given brand config.

I tried the above on both Linux and MacOS and it worked.

**Comment by JacobDel** [comment]
I tried to imitate step 1, but I have this error:
```
jacob@MacBook-Pro react_frontend % yarn build:android                
permission denied: .
```
I made a script to be sure it's running in the same shell, but even this way it isn't working:
```Script
#!/bin/bash

source scripts/load_env.sh
npx react-native run-android
```
```Console
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not create task ':app:generateDebugLintModel'.
      > java.lang.NullPointerException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
```
Which is the error from above (https://github.com/jar0s/reactNative-babel-wla/issues/1#issuecomment-1537453470)

But it's interesting that it does work with your macos system. I'll let you know when I find a fix

**Comment by jar0s** [comment]
That permission problem with `.` is interesting.
What if you tried using `source` command instead? So it would be: `"build:android": "source scripts/load_env.sh && cd android && ./gradlew bundleRelease"` then.

**Comment by JacobDel** [comment]
Something like "source is not a recognized command"
